### PR TITLE
Prefetch

### PR DESCRIPTION
**Pull request by jbrowne6**
I add the mm_prefetch using the intrinsic headers.  @falkben can you test this on windows.  It needs more work but I want to see if it will compile on windows.

### CODE REVIEW

**Comment by falkben** [comment]
This is what I am getting when running the compiling command using visual studio build tools:

```ps
C:\Users\ben\Documents\repos\neurodata\RerF\packedForest>cl /EHsc src\fp.cpp /openmp
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

fp.cpp
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(26): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::chrono::steady_clock::time_point' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: could be 'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &&)'
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: or       'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(const std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(26): note: while trying to match the argument list '(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>, std::chrono::steady_clock::time_point)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(30): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::chrono::steady_clock::time_point' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: could be 'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &&)'
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: or       'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(const std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(30): note: while trying to match the argument list '(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>, std::chrono::steady_clock::time_point)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(336): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(469): note: see reference to class template instantiation 'fp::binStruct<T,Q>' being compiled
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(374): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(408): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(445): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\baseFunctions/fpForest.h(11): warning C4273: 'omp_set_dynamic': inconsistent dll linkage
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\omp.h(66): note: see previous definition of 'omp_set_dynamic'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\baseFunctions/fpForest.h(14): warning C4273: 'omp_set_num_threads': inconsistent dll linkage
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\omp.h(41): note: see previous definition of 'omp_set_num_threads'

C:\Users\ben\Documents\repos\neurodata\RerF\packedForest>cl /EHsc src\fp.cpp /openmp
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

fp.cpp
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(26): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::chrono::steady_clock::time_point' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: could be 'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &&)'
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: or       'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(const std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(26): note: while trying to match the argument list '(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>, std::chrono::steady_clock::time_point)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(30): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::chrono::steady_clock::time_point' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: could be 'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &&)'
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: or       'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(const std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(30): note: while trying to match the argument list '(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>, std::chrono::steady_clock::time_point)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(341): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(474): note: see reference to class template instantiation 'fp::binStruct<T,Q>' being compiled
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(379): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(413): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(450): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\baseFunctions/fpForest.h(11): warning C4273: 'omp_set_dynamic': inconsistent dll linkage
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\omp.h(66): note: see previous definition of 'omp_set_dynamic'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\baseFunctions/fpForest.h(14): warning C4273: 'omp_set_num_threads': inconsistent dll linkage
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\omp.h(41): note: see previous definition of 'omp_set_num_threads'
```

**Comment by falkben** [comment]
I now get the following: 

```ps
cl /EHsc src\fp.cpp /openmp
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27026.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

fp.cpp
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(26): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::chrono::steady_clock::time_point' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: could be 'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &&)'
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: or       'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(const std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(26): note: while trying to match the argument list '(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>, std::chrono::steady_clock::time_point)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(30): error C2679: binary '=': no operator found which takes a right-hand operand of type 'std::chrono::steady_clock::time_point' (or there is no acceptable conversion)
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: could be 'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &&)'
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\chrono(250): note: or       'std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>::operator =(const std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration> &)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\basefunctions\displayProgress.h(30): note: while trying to match the argument list '(std::chrono::time_point<std::chrono::system_clock,std::chrono::system_clock::duration>, std::chrono::steady_clock::time_point)'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(341): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(474): note: see reference to class template instantiation 'fp::binStruct<T,Q>' being compiled
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(379): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(413): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\foresttypes\binnedtree\binStruct.h(450): error C3005: 'update': unexpected token encountered on OpenMP 'atomic' directive
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\baseFunctions/fpForest.h(11): warning C4273: 'omp_set_dynamic': inconsistent dll linkage
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\omp.h(66): note: see previous definition of 'omp_set_dynamic'
c:\users\ben\documents\repos\neurodata\rerf\packedforest\src\baseFunctions/fpForest.h(14): warning C4273: 'omp_set_num_threads': inconsistent dll linkage
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include\omp.h(41): note: see previous definition of 'omp_set_num_threads'
```

**Comment by jbrowne6** [comment]
I forgot about the chrono problem.  I'll add that to my list.

**Comment by falkben** [comment]
I am getting segfaults on this branch when using `binnedBaseRerF` forest type.  This PR was branched from `ben/maxDepth` instead of staging (and didn't have all the latest commits on this branch).  Instead of trying to fix up this branch and force pushing and/or resolving conflicts I created a new branch off staging with the three prefetch commits from this branch @jbrowne6.  It's here https://github.com/neurodata/RerF/tree/ben/prefetch

**Pull request closed without merging**
