### PR TITLE
add check for maxDepth.

### PR DESCRIPTION
**Pull request by MrAE**
to test run `./bin/fp 9 3 4`

It doesn't work for me.  Even when setting shouldProcessNode to return `false`

### CODE REVIEW

**Comment by MrAE** [comment]
@falkben So, I merged in the `Rbindings` branch and then the `ben/maxDepth-setting`

Using this test file `https://gist.github.com/MrAE/670fc39fa7611c7e495a158a7a4d87d0`

I get the following results on MNIST with `binnedBase`
```
starting tree 1
max depth: 27
avg depth: 11.1808
num leaf nodes: 81381
[1] 0.8955
```

**Comment by MrAE** [comment]
The reason this is failing is because src files are above the `R-project` directory and do not get include on build with `R CMD build .`

If you install it from the directory with `Rscript -e "install.packages('./', type = 'source', repos = NULL)"` it works, but this is not a viable option for v2.0.4 to CRAN.

**Comment by falkben** [comment]
What's the error with a CSV file input?

Re: cran - if we can build it and submit a zip file isn't that all that matters?

**Comment by MrAE** [comment]
The error rate with CSV input is bad too.

**Pull request closed without merging**
