### PR TITLE
Add scaling to [0,1] at each node

### PR DESCRIPTION
**Pull request by MrAE**
It's a start to generalized scaling at each node.

### CODE REVIEW

**Comment by MrAE** [comment]
Found an issue when trying to run the README.Rmd.
🚧 Please stand by

**Comment by MrAE** [comment]
This is waiting on some QC tests before we believe that it's working as expected.

**Comment by MrAE** [comment]
Should double check the `RunPredictLeaf.R` function.

**Comment by falkben** [comment]
closing for now, feel free to re-open when ready

**Pull request closed without merging**
